/*

 CORTE DE CONTROL
 ----------------

 ES UNA ESTRATEGIA O ALGORITMO QUE SE UTILIZA PARA OBTENER RESULTADOS, GOZANDO DEL BENEFICIO DE TENER
 LA INFORMACIÓN ORDENADA, AGRUPADA U OPRGANIZADA POR ALGUNA REFERENCIA (VARIABLE O CAMPO DE UN ARCHIVO).

 CORTE DE CONTROL APLICADO A LOS ARCHIVOS
 ----------------------------------------

 ***PREMISAS***

- EL ARCHIVO DEBE ESTAR ORDENADO O AGRUPADO U ORGANIZADO POR AL MENOS UN CAMPO.

- DEBEN EXISTIR VARIOS REGISTROS PARA CADA LOTE DE DATOS ORDENADO.

- POR LO GENERAL, LA CANTIDAD DE REGISTROS DEL ARCHIVO ES DESCONOCIDA.

- SE DEBE CONTAR CON UNA VARIABLE DE TIPO AUXILIAR (ANTERIOR) POR CADA CAMPO POR EL QUE ESTÁ
  ORDENADO EL ARCHIVO. CADA VARIABLE AUXILIAR DEBE TENER EL MISMO TIPO DE DATO QUE EL CAMPO
  POR EL QUE ESTÁ ORDENADO EL ARCHIVO.

- EL VALOR DE LA VARIABLE AUXILIAR SE DEBE ASIGNAR PREVIO AL INGRESO DEL CICLO DE CORTE DE CONTROL.

- POR CADA NIVEL DE CORTE SE DEBE UTILIZAR UN CICLO DE ITERACIÓN CONDICIONADA (WHILE/DO - WHILE)
  CADA CICLO DE CORTE HEREDA LA CONDICIÓN DEL CICLO ANTERIOR Y COLOCA SU PROPIA CONDICIÓN DE CORTE.
  LAS CONDICIONES DEL CICLO SE RELACIONAN CON EL OPERADOR AND (&&).

- SI EL ARCHIVO ESTÁ ORDENADO POR UN CAMPO SE APLICA CORTE DE CONTROL SIMPLE O DE NIVEL 1, SI ESTÁ ORDENADO
  POR 2 CAMPOS SE APLICA CORTE DE CONTROL DE DOS NIVELES O COMPUESTO, Y ASÍ SUCESIVAMENTE.

- LA LECTURA DEL SIGUIENTE REGISTRO DEL ARCHIVO SE DEBE REALIZAR DENTRO DEL CICLO MÁS INTERNO DE CORTE.

NOTA: QUE EL ENUNCIADO INDIQUE QUE UN ARCHIVO O VARIOS ESTÉN ORDENADOS POR UNO O VARIOS CAMPOS, NO IMPLICA QUE
      SE DEBE APLICAR EL CORTE DE CONTROL PARA LA RESOLUCIÓN, ESTA ESTRATEGIA SE DEBE APLICAR SIEMPRE Y CUANDO
      LO QUE SOLICITE EL ENUNCIADO AMERITE EL USO DE ESTA ESTRATEGIA.
      SE DEBE TENER ESPECIAL ATENCIÓN EN DONDE SE UBICAN LOS ALGORITMOS ADQUIRIDOS EN LOS TEMAS ANTERIORES EN
      EL USO DE ESTA ESTRATEGIA, POR EJEMPLO: SI SE COLOCAN PREVIO AL CORTE DE CONTROL, ADENTRO DEL CORTE DE CONTROL,ETC.




*/

#include <stdio.h>

struct MOVI{

 int nrosuc; //Orden del archivo.
 int nrocaja;
 int mes;
 int dia;
 int codop;//1 - Depósito, 2 - Extracción.
 float impo;
};


int main()
{
    FILE * pf;

    int aux_nrocaja;//DECLARACIÓN DE LA VARIABLE AUXILIAR.
                    //DEBE TENER EL MISMO TIPO DE DATO QUE EL CAMPO POR EL QUE ESTÁ ORDENADO EL ARCHIVO.

    int cont;

    struct MOVI movi;


    if((pf=fopen("ARCH_MOVI.DAT","rb"))==NULL)
    {
         puts("Error al abrir el archivo ARCH_MOVI.DAT");
         getch();
         exit(1);
    }


    printf("NRO DE CUENTA - CANTIDAD DE MOVIMIENTOS\n");

    //RECORRER EL ARCHIVO ARCH_MOVI.DAT
    fread(&movi,sizeof(struct MOVI),1,pf);

    while(!feof(pf))
         {
            aux_nrocaja=movi.nrocaja;//ASIGNACIÓN DEL VALOR A LA VAR. AUXILIAR PREVIO AL INGRESO AL CORTE DE CONTROL.


            //BLOQUE DE INICIALIZACIÓN DE VARIABLES QUE SE PROCESAN ADENTRO DEL CORTE DE CONTROL.

            cont=0;//CONTAR LOS MOVIMIENTOS DE CADA CUENTA.


            while(!feof(pf) && aux_nrocaja==movi.nrocaja) /*CORTE DE CONTROL SIMPLE (UN NIVEL):
                                                            EL CICLO HEREDA LAS CONDICIONES DEL CICLO ANTERIOR Y AGREGA
                                                            SU PROPIA CONDICIÓN DE CORTE A TRAVÉS DE OPERADOR LÓGICO AND.
                                                          */

                 {
                    cont++;

                    /*
                      SI EL ARCHIVO ARCH_MOVI.DAT ESTUVIESE ORDENADO POR NROCUENTA Y POR DIA.
                      diant=movi.dia -->ASIGNACIÓN DEL VALOR A LA VAR. AUXILIAR PREVIO AL INGRESO AL CORTE DE CONTROL.

                      while (!feof(pf) && aux_nrocaja==movi.nrocaja && diant=movi.dia)--> CORTE DE CONTROL COMPUESTO: 2 NIVELES.
                             {
                               ...
                               ...
                               ...
                               fread(&movi,sizeof(struct MOVI),1,pf);//LA LECTURA DEL SIGUIENTE REGISTRO SE REALIZA DENTRO DEL CICLO MÁS INTERNO.
                             }

                    */

                    fread(&movi,sizeof(struct MOVI),1,pf);//LA LECTURA DEL SIGUIENTE REGISTRO SE REALIZA DENTRO DEL CICLO MÁS INTERNO.
                 }

                 //PARA EXHIBIR EL LOTE QUE SE PROCESÓ: EL VALOR LO TIENE SIEMPRE LA VARIABLE AUXILIAR.
                 printf("\n %10d %15d",aux_nrocaja,cont);//INFORMA LA CANTIDAD DE MOVIMIENTOS DE CADA CUENTA.

                 //CAMBIO DEL VALOR DE LOTE, OTRA NRO DE CUENTA.


         }
    fclose(pf);
    getch();
    return 0;


}






